
.PHONY: clean all

all: fjlog liblog.a

clean: 
	rm fjlog liblog.a 

liblog.a: log.c log.h
	gcc -c -o log.o -DWIN32 -g -I ../mmf log.c
	ar rcs liblog.a log.o

fjlog: fjlog.c liblog.a
	gcc -o fjlog -DWIN32 -g fjlog.c -I../mmf -L. -llog -L../mmf -lmmf 


