
all: rpcd client librpc.a 

rpcd: librpc.a rpcd-main.c 
	cc -o rpcd -g rpcd-main.c -lcrypto -L. -lrpc 

client: client.c librpc.a 
	cc -o client -g client.c -lcrypto -L. -lrpc 

librpc.a: rpc.c rpcd.c rpc.h rpcd.h shauth.c shauth.h 
	cc -c rpc.c rpcd.c shauth.c 
	ar rcs librpc.a rpc.o rpcd.o shauth.o 
	
.PHONY: tar clean all 
tar:
	tar -czvf rpc.tar.gz rpc.h rpc.c Makefile rpcd.c client.c shauth.h shauth.c rpcd-main.c 

clean:
	rm client rpcd rpc.o rpcd.o librpc.a shauth.o 
