
.PHONY: all clean 

all: libraft.a raft

clean:
	rm -f libraft.a raft.o raft

libraft.a: raft.c raft.h raft-rpc.c 
	cc -c -g raft.c raft-rpc.c -I../mmf -I../rpc -I../hostreg -I../log -I../sec 
	ar rcs libraft.a raft.o raft-rpc.o 

raft: libraft.a raft-main.c
	cc -o raft -g raft-main.c -L. -lraft -I../mmf -L../mmf -lmmf -I../sec -L../sec -lsec -lcrypto -L../rpc -lrpc -I../hostreg -L../hostreg -lhostreg -I../log -L../log -llog 
	