;;;
;;; This file was generated by fvmc pascal compiler
;;; Date: 13:07:19 Jul 27 2020
;;; 
	.MODULE		testRpc
	.PROGRAM	2333333	1
	.DATA	hello	"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"

;; ----- PROCEDURE ProcNull(argcount : INTEGER, argbuf : OPAQUE, VAR rescount : INTEGER, VAR resbuf : OPAQUE) ----- 

ProcNull:
	LDI	R0	0
	LDSP	R1	-12	 ; get address of rescount
	ST	R1	R0	 ; store into rescount
	LDI	R0	0
	LDSP	R1	-8	 ; get address of resbuf
	ST	R1	R0	 ; store into resbuf
	RET

	.TEXT	HelloWorld	"Hello, World!"

;; ----- PROCEDURE ProcHello(argcount : INTEGER, argbuf : OPAQUE, VAR rescount : INTEGER, VAR resbuf : OPAQUE) ----- 

ProcHello:
	ADDSP	4	 ; allocate locals
	LDI	R0	HelloWorld
	STSP	R0	-4	 ; store local p
	LDSP	R0	-4
	LD	R0	R0
	LDSP	R1	-16	 ; get address of rescount
	ST	R1	R0	 ; store into rescount
	LDSP	R0	-16	 ; load param rescount
	LD	R0	R0
	ADD	R0	4
	LDSP	R1	-16	 ; get address of rescount
	ST	R1	R0	 ; store into rescount
	LDI	R0	HelloWorld
	LDSP	R1	-12	 ; get address of resbuf
	ST	R1	R0	 ; store into resbuf
	SUBSP	4	 ; free locals
	RET


;; ----- PROCEDURE ProcEcho(argcount : INTEGER, argbuf : OPAQUE, VAR rescount : INTEGER, VAR resbuf : OPAQUE) ----- 

ProcEcho:
	LDSP	R0	-20	 ; load param argcount
	LDSP	R1	-12	 ; get address of rescount
	ST	R1	R0	 ; store into rescount
	LDSP	R0	-16	 ; load param argbuf
	LDSP	R1	-8	 ; get address of resbuf
	ST	R1	R0	 ; store into resbuf
	RET

	.DATA	counter	0

;; ----- PROCEDURE ProcCounter(argcount : INTEGER, argbuf : OPAQUE, VAR rescount : INTEGER, VAR resbuf : OPAQUE) ----- 

ProcCounter:
	LD	R0	counter
	ADD	R0	1
	LDI	R1	counter
	ST	R1	R0
	LDI	R0	counter
	LDSP	R1	-8	 ; get address of resbuf
	ST	R1	R0	 ; store into resbuf
	LDI	R0	4
	LDSP	R1	-12	 ; get address of rescount
	ST	R1	R0	 ; store into rescount
	RET

	.EXPORT		ProcNull
	.EXPORT		ProcHello
	.EXPORT		ProcEcho
	.EXPORT		ProcCounter
	.EXPORT		hello
