
;;; This file contains the proc ids of the native functions

	.CONST		MODULE-NATIVE		0
	.CONST		NATIVE-NOP		0
	.CONST		NATIVE-PUTS		1
	.CONST		NATIVE-RAND		2
	.CONST 		NATIVE-NOW 		3
	.CONST		NATIVE-LOGSTR		4
	.CONST		NATIVE-READ		5
	.CONST		NATIVE-WRITE		6
	.CONST		NATIVE-GETPROGID	7
	.CONST		NATIVE-WRITELOG		8
	.CONST		NATIVE-READLOG		9
	
	

	
