	.CONST	NativeNop	0
	.CONST	NativePuts	1
	.CONST	NativeRand	2
	.CONST	NativeNow	3
	.CONST	NativeLogStr	4
	.CONST	NativeProgidByName	5
	.CONST	NativeProcidByName	6
	.CONST	NativeWriteLog	7
	.CONST	NativeReadLog	8
	.CONST	NativeYield	10
	.CONST	YieldFork	1
